DBCON-222: Implement query-single operation.
mulesoft/mule-db-connector pull request #325
Opened 2020-11-05 12:43 UTC by emariotti3

2020-11-06 18:59 UTC, julodiaz requested changes

2020-11-06 18:59 UTC, julodiaz commented on src/main/java/org/mule/extension/db/internal/result/row/NonStreamingInsensitiveMapRowHandler.java
> +
Delete blank space.

2020-11-06 18:59 UTC, julodiaz commented on src/main/java/org/mule/extension/db/internal/result/row/NonStreamingInsensitiveMapRowHandler.java
> +
Delete blank space.

2020-11-06 18:59 UTC, julodiaz commented on src/main/java/org/mule/extension/db/internal/result/row/NonStreamingInsensitiveMapRowHandler.java
> +public class NonStreamingInsensitiveMapRowHandler extends InsensitiveMapRowHandler {
Add little comment/justification for the existence of this new class.

2020-11-06 20:12 UTC, estebanwasinger requested changes

2020-11-06 20:12 UTC, estebanwasinger commented on src/main/java/org/mule/extension/db/internal/result/resultset/SingleResultSetHandler.java
> +public class SingleResultSetHandler implements ResultSetCharsetEncodedHandler {
jdoc

2020-11-06 20:12 UTC, estebanwasinger commented on src/main/java/org/mule/extension/db/internal/operation/DmlOperations.java
> +  public Map<String, Object> querySingle(@ParameterGroup(name = QUERY_GROUP) @Placement(
jdoc

2020-11-10 22:46 UTC, julodiaz approved these changes

2020-11-11 13:05 UTC, estebanwasinger requested changes

2020-11-11 13:05 UTC, estebanwasinger commented on src/main/java/org/mule/extension/db/internal/operation/DmlOperations.java
> +  public Map<String, Object> querySingle(@ParameterGroup(name = QUERY_GROUP) @Placement(
the Jdoc is also used for Mulesoft public docs try to give more love to it. ❤️

2020-11-11 13:05 UTC, estebanwasinger requested changes

2020-11-11 13:05 UTC, estebanwasinger commented on src/main/java/org/mule/extension/db/internal/domain/metadata/QuerySingleMetadataResolver.java
> +public class QuerySingleMetadataResolver extends SelectMetadataResolver {
jdoc

2020-11-16 13:18 UTC, estebanwasinger approved these changes

2020-11-16 13:22 UTC, julodiaz approved these changes

2020-11-16 13:39 UTC, nicomz approved these changes

2020-11-16 13:40 UTC, merged