DBCON-283:  avoid transitive packages exposure.
mulesoft/mule-db-connector pull request #415
Opened 2021-06-11 15:41 UTC by nicomz

2021-06-14 16:01 UTC, juldiazmule commented on src/main/java/org/mule/extension/db/internal/DbConnector.java
> -import org.mule.extension.db.api.logger.LoggerApiPackage;
Shouldn't we continue to export LoggerApiPackage for MuleMySqlLogger?

2021-06-14 19:34 UTC, estebanwasinger approved these changes

2021-06-23 14:27 UTC, marianogonzalez requested changes

2021-06-23 14:27 UTC, marianogonzalez commented on src/main/java/org/mule/extension/db/internal/domain/connection/datasource/DbDataSourceReferenceConnectionProvider.java
> +public class DbDataSourceReferenceConnectionProvider extends DbConnectionProvider {
I don't see a reason why the client cannot contain a `DatasourceReferenceConnectionProvider` implementation and the connector simply extends it adding this annotations. This class is not exporting anything.

2021-06-23 14:27 UTC, marianogonzalez commented on src/main/java/org/mule/extension/db/internal/domain/connection/derby/DerbyConnectionProvider.java
> +    super.columnTypes = columnTypes;
this seems unnecesary. The SDK will pick up the `@Parameters` in the super class

2021-06-23 14:27 UTC, marianogonzalez commented on src/main/java/org/mule/extension/db/internal/domain/connection/generic/DbGenericConnectionProvider.java
> +public class DbGenericConnectionProvider extends DbConnectionProvider {
same as before

2021-06-23 14:27 UTC, marianogonzalez commented on src/main/java/org/mule/extension/db/internal/domain/connection/mysql/MySqlConnectionProvider.java
>    private MySqlConnectionParameters mySqlParameters;
same as before

2021-06-24 14:15 UTC, marianogonzalez approved these changes

2021-06-24 20:44 UTC, merged