OracleDbConnection: Close the JDBC Statement in getTables().
mulesoft/mule-db-connector pull request #471
Opened 2021-11-03 16:59 UTC by niqueco

2021-11-03 17:30 UTC, juldiazmule commented on src/main/java/org/mule/extension/db/internal/domain/connection/oracle/OracleDbConnection.java
> +      return tables;
Add a line-break between "}" and "return"

2021-11-03 17:39 UTC, juldiazmule commented
- please create a Jira ticket under DBCON project to track this change
- add a simple functional test that verifies if method "close" is called on the mocked statement

2021-11-03 21:00 UTC, nicomz requested changes

2021-11-03 21:00 UTC, nicomz commented on src/test/java/org/mule/extension/db/internal/domain/connection/OracleDbConnectionTestCase.java
> +import java.sql.*;
No wildcard imports.

2021-11-03 21:00 UTC, nicomz commented on src/test/java/org/mule/extension/db/internal/domain/connection/OracleDbConnectionTestCase.java
> +  public void getTablesClosesTheStatement() throws SQLException {
Please run formatter.

2021-11-04 15:20 UTC, juldiazmule submitted a review, later dismissed

2021-11-04 19:10 UTC, nicomz approved these changes, later dismissed

2021-11-11 12:45 UTC, nicomz approved these changes

2021-11-11 13:46 UTC, merged