Chore/dbcon update
mulesoft/mule-db-connector pull request #543
Opened 2022-02-08 14:38 UTC by catrielzz

2022-02-08 17:54 UTC, giss-ignacio requested changes

2022-02-08 17:54 UTC, giss-ignacio commented on src/test/munit/config.xml
> +    <db:config name="mySqlDbLocal">
this should be removed if not used

2022-02-08 18:30 UTC, catrielzz commented on src/test/munit/config.xml
> +    <db:config name="mySqlDbLocal">
done!

2022-02-22 15:49 UTC, giss-ignacio approved these changes

2022-02-23 12:47 UTC, merged